version: "3.7"

services:
  app_proxy:
    environment:
    # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: homer_server_1
      APP_PORT: 8080

  server:
    image: gbaygon/homer:latest
    volumes:
      - ${APP_DATA_DIR}/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    restart: on-failure